"""
gRPC server implementing the unified ``Generator`` service.

The gRPC service provides a ``Generate`` RPC that mirrors the FastAPI
``/generate`` endpoint.
"""

from concurrent import futures
from pathlib import Path
from typing import Optional

import grpc
import torch
from peft import PeftModel
from transformers import AutoTokenizer, pipeline

from ..llm.model import load_model
from ..llm.config import QLoRAConfig
from ..training.dataset import format_fields


# ---------------------------------------------------------------------------
# Proto stubs (generated at build time — see proto/service.proto)
# ---------------------------------------------------------------------------

# In a production build these would be auto-generated by ``grpc_tools``.
# For development we declare the stub interface so the module loads cleanly.
try:
    from market_news_pb2 import GenerateRequest, GenerateResponse
    from market_news_pb2_grpc import GeneratorServicer, add_GeneratorServicer_to_server
except ImportError:
    # Placeholder stubs for development / type-checking
    class GenerateRequest:  # type: ignore[no-redef]
        event_context: str = ""
        econ_indicators: str = ""

    class GenerateResponse:  # type: ignore[no-redef]
        headline: str = ""
        sentiment_score: float = 0.0

    class GeneratorServicer:  # type: ignore[no-redef]
        pass

    def add_GeneratorServicer_to_server(servicer, server):  # type: ignore[misc]
        pass


# ---------------------------------------------------------------------------
# gRPC Servicer
# ---------------------------------------------------------------------------

class MarketNewsGeneratorServicer(GeneratorServicer):
    """gRPC servicer that wraps the loaded model for financial news generation."""

    def __init__(
        self,
        base_model_id: str,
        adapter_path: Optional[str] = None,
        qlora: Optional[QLoRAConfig] = None,
        device: str = "cuda:0",
    ):
        if qlora is None:
            qlora = QLoRAConfig()

        model = load_model(base_model_id, qlora=qlora, device_map=device)

        if adapter_path is not None:
            model = PeftModel.from_pretrained(model, adapter_path)
            model = model.merge_and_unload()

        model.eval()

        tokenizer = AutoTokenizer.from_pretrained(base_model_id)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        self._pipeline = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            device_map=device,
        )
        self._tokenizer = tokenizer

    def Generate(self, request: GenerateRequest, context: grpc.ServicerContext) -> GenerateResponse:
        """Handle a Generate RPC — produce headline + sentiment score."""
        prompt = format_fields(
            event_context=request.event_context,
            econ_indicators=request.econ_indicators,
            headline="",
            sentiment_score=0.0,
        )

        outputs = self._pipeline(
            prompt,
            max_new_tokens=128,
            temperature=0.7,
            do_sample=True,
            pad_token_id=self._tokenizer.pad_token_id,
            eos_token_id=self._tokenizer.eos_token_id,
            return_full_text=False,
        )

        generated_text: str = outputs[0]["generated_text"]

        headline = ""
        sentiment_score = 0.0
        for line in generated_text.strip().split("\n"):
            if line.startswith("Headline:"):
                headline = line[len("Headline:"):].strip()
            elif line.startswith("Sentiment Score:"):
                raw = line[len("Sentiment Score:"):].strip()
                try:
                    sentiment_score = float(raw)
                except ValueError:
                    sentiment_score = 0.0

        resp = GenerateResponse()
        resp.headline = headline or generated_text.strip()
        resp.sentiment_score = sentiment_score
        return resp


# ---------------------------------------------------------------------------
# Server runner
# ---------------------------------------------------------------------------

def serve_grpc(
    base_model_id: str = "google/gemma-4-12b-it",
    adapter_path: Optional[str] = None,
    host: str = "0.0.0.0",
    port: int = 50051,
    max_workers: int = 4,
) -> None:
    """Start the gRPC server (blocking)."""
    servicer = MarketNewsGeneratorServicer(
        base_model_id=base_model_id,
        adapter_path=adapter_path,
    )

    server = grpc.server(futures.ThreadPoolExecutor(max_workers=max_workers))
    add_GeneratorServicer_to_server(servicer, server)
    server.add_insecure_port(f"{host}:{port}")
    server.start()
    print(f"gRPC server listening on {host}:{port}")
    server.wait_for_termination()